apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - image: pavanikakarlapudi/stress:v1
      imagePullPolicy: Always
      name: stress
      command: ["sleep", "200"]
      resources:
        requests:
          cpu: "150"
          memory: "200mi"
        limits:
          cpu: "200m"
          memory: "300mi"
